import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "@/redux/cart/Providers";
import NextTopLoader from 'nextjs-toploader';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <NextTopLoader
          color="#415782"
          height={2}
          initialPosition={0.08}
          easing="ease"
          zIndex={1600}
          crawl={true}
          showSpinner={true}
          crawlSpeed={400}
        />
        <Providers>
          <Navbar />
          {children}
          
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
